<?php
define('ABSPATH',__DIR__); function __($s){return $s;} function sanitize_text_field($s){return trim(strip_tags((string)$s));} function sanitize_key($s){return preg_replace('/[^a-z0-9_\-]/','',strtolower($s));} function wp_parse_url($u,$c=-1){return parse_url($u,$c);} function is_wp_error($v){return false;} function wp_generate_uuid4(){return 'test-lock-token';}
$GLOBALS['opts']=array();function get_option($k,$d=array()){return $GLOBALS['opts'][$k]??$d;}function add_option($k,$v){if(isset($GLOBALS['opts'][$k]))return false;$GLOBALS['opts'][$k]=$v;return true;}function delete_option($k){unset($GLOBALS['opts'][$k]);return true;}
class WC_Order{private$id;private$m=array();private$status='processing';private$total='100';private$ship='10';public$notes=array();function __construct($id,$m=array()){$this->id=$id;$this->m=$m;}function get_id(){return$this->id;}function get_meta($k,$s=true){return$this->m[$k]??'';}function update_meta_data($k,$v){$this->m[$k]=$v;}function save(){}function add_order_note($n){$this->notes[]=$n;}function get_status(){return$this->status;}function get_total(){return$this->total;}function get_shipping_total(){return$this->ship;}}
$n=0;function ok($v,$m){global $n;++$n;if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$api=dirname(__DIR__).'/includes/api/';foreach(array('class-spx-api-error-mapper','class-spx-api-response','class-spx-api-config','class-spx-request-signer','interface-spx-http-client','class-spx-tracking-service','class-spx-tracking-status-mapper') as $f){require_once $api.$f.'.php';}
$service=$api.'class-spx-cancel-service.php';$manager=dirname(__DIR__).'/includes/shipment/class-spx-cancel-manager.php';ok(file_exists($service)&&file_exists($manager),'cancel production classes exist');require_once $service;require_once $manager;
class CancelFake implements SPX_Http_Client_Interface{public $response;public $calls=0;public $body;function request(string $p,array $b):SPX_API_Response{$this->calls++;$this->body=$b;return $this->response;}}
function cr($data){return SPX_API_Response::from_http(200,json_encode(array('ret_code'=>0,'data'=>$data)));}foreach(array('SPX_TEST_BASE_URL'=>'https://test-stable.spx.vn/','SPX_TEST_APP_ID'=>'1','SPX_TEST_APP_SECRET'=>'s','SPX_TEST_USER_ID'=>'2','SPX_TEST_USER_SECRET'=>'u')as$k=>$v){putenv("$k=$v");}
$f=new CancelFake();$f->response=cr(array('tracking_no_list'=>array('SPXVN123456789'),'fail_list'=>array()));$r=(new SPX_Cancel_Service(SPX_API_Config::for_test(),$f))->cancel(array('SPXVN123456789'));ok($r['SPXVN123456789']['state']==='succeeded','cancel success parsed');ok($f->calls===1&&$f->body['tracking_no_list']===array('SPXVN123456789'),'cancel request mapped and called once');
$f=new CancelFake();$f->response=cr(array('tracking_no_list'=>array(),'fail_list'=>array(array('tracking_no'=>'SPXVN123456789','ret_code'=>13002,'debug_msg'=>'private'))));$r=(new SPX_Cancel_Service(SPX_API_Config::for_test(),$f))->cancel(array('SPXVN123456789'));ok($r['SPXVN123456789']['state']==='failed'&&$r['SPXVN123456789']['ret_code']===13002,'business failure parsed');ok(false===strpos(json_encode($r),'private'),'cancel debug omitted');
$f=new CancelFake();$f->response=SPX_API_Response::from_http(500,'');$r=(new SPX_Cancel_Service(SPX_API_Config::for_test(),$f))->cancel(array('SPXVN123456789'));ok($r['SPXVN123456789']['state']==='unknown','HTTP 5xx becomes unknown');ok($f->calls===1,'unknown cancel is never blindly retried');
foreach(array('1001'=>true,'2006'=>false,'4001'=>false,'5002'=>false,'5003'=>false,'6001'=>false,'6003'=>false,'7001'=>false)as$code=>$allowed){ok(SPX_Cancel_Manager::is_status_eligible($code)===$allowed,'official eligibility '.$code);}
$src=file_get_contents($manager);foreach(array('_spx_cancel_state','processing','succeeded','unknown','failed','spx_cancel_order_','get_by_tracking_number','schedule_canonical_verification')as$x){ok(false!==strpos($src,$x),'manager includes '.$x);}ok(false===strpos($src,'set_status('),'manager never changes Woo status');ok(false===strpos($src,'refund'),'manager never refunds');
class TrackManagerFake{public$result;public$calls=0;function get_by_tracking_number($t){$this->calls++;return$this->result;}}class CancelManagerFake{public$result;public$calls=0;function cancel($t){$this->calls++;return$this->result;}}class UpdateManagerFake{public$calls=0;function apply($o,$r,$s){$this->calls++;}}class SPX_Tracking_Scheduler{public static$calls=0;static function schedule_canonical_verification($id):void{self::$calls++;}}
function tmresult($code,$status){return array('success'=>true,'found'=>true,'tracking_no'=>'SPXVN123456789','status_code'=>$code,'internal_status'=>$status,'customer_label'=>$status,'routes'=>array());}function cmorder($id){return new WC_Order($id,array('_spx_tracking_number'=>'SPXVN123456789','_spx_shipment_environment'=>'test','_spx_shipment_status_code'=>'1001'));}
$track=new TrackManagerFake();$track->result=tmresult('1001','pending_pickup');$cancel=new CancelManagerFake();$cancel->result=array('SPXVN123456789'=>array('success'=>true,'state'=>'succeeded'));$up=new UpdateManagerFake();$order=cmorder(1);$before=array($order->get_status(),$order->get_total(),$order->get_shipping_total());$mgr=new SPX_Cancel_Manager($track,$cancel,$up,true);$res=$mgr->request_cancel($order);ok($res['state']==='succeeded'&&$cancel->calls===1&&$track->calls===1,'canonical check precedes one successful cancel');ok($order->get_meta('_spx_cancel_state')==='succeeded'&&count($order->notes)===1,'success persisted and note added once');$mgr->request_cancel($order);ok($cancel->calls===1&&count($order->notes)===1,'succeeded state blocks duplicate cancel and note');ok($before===array($order->get_status(),$order->get_total(),$order->get_shipping_total()),'Woo status and totals unchanged');
$track=new TrackManagerFake();$track->result=tmresult('1001','pending_pickup');$cancel=new CancelManagerFake();$cancel->result=array('SPXVN123456789'=>array('success'=>false,'state'=>'unknown'));$order=cmorder(2);$mgr=new SPX_Cancel_Manager($track,$cancel,new UpdateManagerFake(),true);$res=$mgr->request_cancel($order);ok($res['state']==='unknown'&&$order->get_meta('_spx_cancel_state')==='unknown','timeout-like result persists unknown');$mgr->request_cancel($order);ok($cancel->calls===1,'unknown state blocks blind retry');
$track=new TrackManagerFake();$track->result=tmresult('2006','out_for_delivery');$cancel=new CancelManagerFake();$order=cmorder(3);$res=(new SPX_Cancel_Manager($track,$cancel,new UpdateManagerFake(),true))->request_cancel($order);ok($res['error_code']==='status_ineligible'&&$cancel->calls===0,'ineligible canonical status never calls cancel');
$lockOrder=cmorder(4);$GLOBALS['opts']['spx_cancel_order_4']=array('expires_at'=>time()+100);$mgr=new SPX_Cancel_Manager();ok(!$mgr->acquire_lock(4),'valid atomic lock blocks concurrent request');$GLOBALS['opts']['spx_cancel_order_4']=array('expires_at'=>time()-1);ok($mgr->acquire_lock(4),'stale lock is safely replaced');delete_option('spx_cancel_order_4');
$track=new TrackManagerFake();$track->result=tmresult('7001','cancelled');$up=new UpdateManagerFake();$order=cmorder(5);$order->update_meta_data('_spx_cancel_state','unknown');$res=(new SPX_Cancel_Manager($track,new CancelManagerFake(),$up,false))->reconcile($order);ok($res['state']==='succeeded'&&$up->calls===1,'reconciliation marks canonical Cancelled and updates timeline');
$repair=cmorder(6);$repair->update_meta_data('_spx_cancel_state','succeeded');$repair->update_meta_data('_spx_cancel_note_added','yes');(new SPX_Cancel_Manager($track,new CancelManagerFake(),new UpdateManagerFake(),false))->reconcile($repair);ok(count($repair->notes)===1,'reconciliation repairs a missing cancel note despite a stale marker');
echo "SPX cancel tests PASS ($n assertions)\n";
