<?php
error_reporting( E_ALL ); define( 'ABSPATH', __DIR__ );
function __( $s ) { return $s; } function sanitize_text_field( $s ) { return trim( strip_tags( (string) $s ) ); } function sanitize_key( $s ) { return preg_replace('/[^a-z0-9_\-]/','',strtolower($s)); } function wp_parse_url( $u, $c=-1 ) { return parse_url($u,$c); } function is_wp_error($v){return false;}
$transients=array(); function set_transient($k,$v,$ttl){global$transients;$transients[$k]=$v;return true;} function get_transient($k){global$transients;return $transients[$k]??false;} function get_current_user_id(){return 1;}
$n=0; function ok($v,$m){global $n;++$n;if(!$v){throw new RuntimeException('FAIL: '.$m);}echo "PASS: $m\n";}
$api=dirname(__DIR__).'/includes/api/'; foreach(array('class-spx-api-error-mapper','class-spx-api-response','class-spx-api-config','class-spx-request-signer','interface-spx-http-client','class-spx-tracking-service') as $f){require_once $api.$f.'.php';}
$label=$api.'class-spx-label-service.php'; $manager=dirname(__DIR__).'/includes/shipment/class-spx-label-manager.php';
ok(file_exists($label)&&file_exists($manager),'label production classes exist'); require_once $label; require_once $manager;
class LabelFake implements SPX_Http_Client_Interface { public $responses=array();public $calls=0;public $bodies=array();function request(string $p,array $b):SPX_API_Response{$this->calls++;$this->bodies[]=$b;return array_shift($this->responses);} }
function lr($data){return SPX_API_Response::from_http(200,json_encode(array('ret_code'=>0,'data'=>$data)));}
foreach(array('SPX_TEST_BASE_URL'=>'https://test-stable.spx.vn/','SPX_TEST_APP_ID'=>'1','SPX_TEST_APP_SECRET'=>'s','SPX_TEST_USER_ID'=>'2','SPX_TEST_USER_SECRET'=>'u') as $k=>$v){putenv("$k=$v");}
$f=new LabelFake();$f->responses[]=lr(array('awb_link'=>'https://label.spx.vn/a.pdf','fail_list'=>array()));$s=new SPX_Label_Service(SPX_API_Config::for_test(),$f);$r=$s->get_shipping_labels(array('SPXVN123456789','SPXVN123456789','SPXMOCK-1',''));
ok($f->calls===1,'valid deduplicated label batch calls API once');ok($f->bodies[0]['tracking_no_list']===array('SPXVN123456789'),'request maps tracking_no_list');ok($r['SPXVN123456789']['success']===true,'combined awb_link maps to successful tracking');ok(false===strpos(json_encode($r),'user_secret'),'result excludes credentials');
$f=new LabelFake();$f->responses[]=lr(array('awb_link'=>'https://label.spx.vn/a.pdf','fail_list'=>array(array('tracking_no'=>'SPXVN222222222','ret_code'=>13201,'debug_msg'=>'private'))));$s=new SPX_Label_Service(SPX_API_Config::for_test(),$f);$r=$s->get_shipping_labels(array('SPXVN111111111','SPXVN222222222'));ok($r['SPXVN111111111']['success']&&!$r['SPXVN222222222']['success'],'partial success preserves successful item');ok(false===strpos(json_encode($r),'private'),'fail_list debug omitted');
$many=array();for($i=0;$i<31;$i++){$many[]='SPXVN'.str_pad((string)$i,9,'0',STR_PAD_LEFT);}$f=new LabelFake();$f->responses[]=lr(array('awb_link'=>'https://label.spx.vn/a.pdf'));$f->responses[]=lr(array('awb_link'=>'https://label.spx.vn/b.pdf'));(new SPX_Label_Service(SPX_API_Config::for_test(),$f))->get_shipping_labels($many);ok($f->calls===2,'safe official batch limit 30 chunks 31 inputs');
$v=new SPX_Label_Manager(null,array('label.spx.vn'));ok($v->validate_url('https://label.spx.vn/a.pdf')['valid'],'allowlisted HTTPS label accepted');foreach(array('http://label.spx.vn/a','https://localhost/a','https://127.0.0.1/a','https://10.0.0.1/a','javascript:alert(1)','data:text/plain,x','file:///tmp/x','https://evil.test/a') as $u){ok(!$v->validate_url($u)['valid'],'unsafe label URL rejected: '.$u);}ok(SPX_Label_Manager::CACHE_TTL<=1800,'cache does not exceed official 30-minute TTL');
class WC_Order {private $id;private $m;function __construct($id,$m){$this->id=$id;$this->m=$m;}function get_id(){return $this->id;}function get_meta($k,$s=true){return $this->m[$k]??'';}function update_meta_data($k,$v){$this->m[$k]=$v;}function save(){return $this->id;}}
class LabelManagerFake {public $calls=0;function get_shipping_labels($t){$this->calls++;return array($t[0]=>array('success'=>true,'awb_link'=>'https://label.spx.vn/cached.pdf','format'=>'pdf'));}}
$order=new WC_Order(7,array('_spx_tracking_number'=>'SPXVN123456789','_spx_shipment_environment'=>'test'));$ms=new LabelManagerFake();$m=new SPX_Label_Manager($ms,array('label.spx.vn'));$first=$m->request_for_order($order);$second=$m->request_for_order($order);ok($first['success']&&$second['success']&&$ms->calls===1,'valid short cache prevents a second Label API request');
$src=file_get_contents($manager);ok(false===strpos($src,"update_meta_data( '_spx_label_url'"),'label URL is not persisted in order meta');ok(false===strpos($src,'wp_remote_get'),'manager never downloads label');
echo "SPX label tests PASS ($n assertions)\n";
